export const SITE_NAME = 'Free Financial Calculator Online';
export const SITE_URL = 'https://financialcalculatoronlinefree.com';

/** AdSense publisher ID. Set to '' to render ad slots as empty placeholders. */
export const ADSENSE_PUBLISHER_ID = 'pub-7205603150750890';
export const ADSENSE_CLIENT = ADSENSE_PUBLISHER_ID ? `ca-${ADSENSE_PUBLISHER_ID}` : '';
/** Default display ad unit ("Fincalc slots"); AdSense allows one unit to fill every box on a page. */
export const ADSENSE_DEFAULT_SLOT = '1963056538';

export const TWITTER_HANDLE = '@FinCalcsOnline';
export const TWITTER_URL = 'https://twitter.com/FinCalcsOnline';
/** Square raster logo for structured data and the default share image (generated by `npm run favicons`). */
export const LOGO_URL = `${SITE_URL}/icon-512.png`;

/** PickSafely cross-promotion on the two email picker pages (after a draw, and in the fairness section). */
export const PICKSAFELY_URL = 'https://www.picksafely.com/?utm_source=fincalc&utm_medium=tool&utm_campaign=picker';
